# compose 파일 버전
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "28080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/webserver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    container_name: webserver_database
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: webserver
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--host", "db" ]
      interval: 10s
      retries: 20
      timeout: 5s