# server config
server:
  port: 8080
  max-http-request-header-size: 10MB
# spring application config
spring:
  web:
    resources:
      add-mappings: false
  # mysql database config
  datasource:
    url: jdbc:mysql://localhost:3306/webserver
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


